# Use a base image with Python installed
FROM python:3.9

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the script and requirements file into the container
COPY app/ /usr/src/app/  

# Install dependencies
RUN pip install -r requirements.txt

#run service - Expose (what is the request response model)
EXPOSE 5001

# Define the command to run when the container starts
CMD ["flask", "run", "--host=0.0.0.0"]
#CMD ["python", "langchain_orcid.py"]
